Javalib Core
============

Javalib Core is a common core for all Robot Framework test libraries written in
Java.

Usage instructions can be found on the project Wiki:
https://github.com/robotframework/JavalibCore/wiki

Project jar can be downloaded directly from the `Maven Repository`__

__ http://search.maven.org/remotecontent?filepath=org/robotframework/javalib-core/2.0.3/javalib-core-2.0.3.jar

.. code:: xml

    <dependency>
        <groupId>org.robotframework</groupId>
        <artifactId>javalib-core</artifactId>
        <version>2.0.3</version>
    </dependency>


Although it's prefered to use it as Maven dependency

The project was originally hosted at `Google Code`__

__ http://code.google.com/p/robotframework-javalibcore/
