Javalib Core
============

Javalib Core is a common core for all Robot Framework test libraries written in
Java.

Usage instructions can be found on the project Wiki:
https://github.com/robotframework/JavalibCore/wiki

Rest of this document describes how Javalib-core is developed.

