Javalib Core
============

Javalib Core is a common core for all Robot Framework test libraries written in
Java.

Usage instructions can be found on the project Wiki:
https://github.com/robotframework/JavalibCore/wiki

The project was orginally hosted at `Google Code`__

__ http://code.google.com/p/robotframework-javalibcore/
